# syntax=docker/dockerfile:1
#
#
FROM node:23-alpine AS base
WORKDIR /app
ENV NODE_ENV=production

ARG NODE_BACKEND_ENDPOINT
ARG NODE_ALERT_ENDPOINT
ARG NODE_MODEL_FAST_API_ENDPOINT
ARG NODE_ORCHESTRATOR_ENDPOINT

ARG VITE_BACKEND_ENDPOINT
ARG VITE_ALERT_ENDPOINT
ARG VITE_MODEL_FAST_API_ENDPOINT
ARG VITE_ORCHESTRATOR_ENDPOINT
ARG VITE_ORCHESTRATOR_PATH_PREFIX
ARG VITE_BACKEND_TOKEN
ARG VITE_ALERT_TOKEN
ARG VITE_CASE_TOKEN
ARG VITE_ORCHESTRATOR_TOKEN

ENV NODE_BACKEND_ENDPOINT=$NODE_BACKEND_ENDPOINT
ENV NODE_ALERT_ENDPOINT=$NODE_ALERT_ENDPOINT
ENV NODE_MODEL_FAST_API_ENDPOINT=$NODE_MODEL_FAST_API_ENDPOINT
ENV NODE_ORCHESTRATOR_ENDPOINT=$NODE_ORCHESTRATOR_ENDPOINT

ENV VITE_BACKEND_ENDPOINT=$VITE_BACKEND_ENDPOINT
ENV VITE_ALERT_ENDPOINT=$VITE_ALERT_ENDPOINT
ENV VITE_MODEL_FAST_API_ENDPOINT=$VITE_MODEL_FAST_API_ENDPOINT
ENV VITE_ORCHESTRATOR_ENDPOINT=$VITE_ORCHESTRATOR_ENDPOINT
ENV VITE_ORCHESTRATOR_PATH_PREFIX=$VITE_ORCHESTRATOR_PATH_PREFIX
ENV VITE_BACKEND_TOKEN=$VITE_BACKEND_TOKEN
ENV VITE_ALERT_TOKEN=$VITE_ALERT_TOKEN
ENV VITE_CASE_TOKEN=$VITE_CASE_TOKEN
ENV VITE_ORCHESTRATOR_TOKEN=$VITE_ORCHESTRATOR_TOKEN

RUN apk update && apk upgrade && \
	apk add --no-cache libc6-compat && \
	npm install -g corepack && \
	corepack enable && \
	corepack prepare yarn@4.9.1 --activate

COPY . .
COPY ./src/main.tsx ./src/main.tsx 
RUN ls -la
RUN ls -la ./src/
RUN yarn install --immutable
RUN yarn build

#
#
FROM base AS production
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

ARG NODE_BACKEND_ENDPOINT
ARG NODE_ALERT_ENDPOINT
ARG NODE_MODEL_FAST_API_ENDPOINT
ARG NODE_ORCHESTRATOR_ENDPOINT

ARG VITE_BACKEND_ENDPOINT
ARG VITE_ALERT_ENDPOINT
ARG VITE_MODEL_FAST_API_ENDPOINT
ARG VITE_ORCHESTRATOR_ENDPOINT

ENV NODE_BACKEND_ENDPOINT=$NODE_BACKEND_ENDPOINT
ENV NODE_ALERT_ENDPOINT=$NODE_ALERT_ENDPOINT
ENV NODE_MODEL_FAST_API_ENDPOINT=$NODE_MODEL_FAST_API_ENDPOINT
ENV NODE_ORCHESTRATOR_ENDPOINT=$NODE_ORCHESTRATOR_ENDPOINT

ENV VITE_BACKEND_ENDPOINT=$VITE_BACKEND_ENDPOINT
ENV VITE_ALERT_ENDPOINT=$VITE_ALERT_ENDPOINT
ENV VITE_MODEL_FAST_API_ENDPOINT=$VITE_MODEL_FAST_API_ENDPOINT
ENV VITE_ORCHESTRATOR_ENDPOINT=$VITE_ORCHESTRATOR_ENDPOINT

RUN apk add --no-cache libc6-compat

# Copy built artifacts from builder stage
COPY --from=base --chown=node:node /app/dist ./dist
COPY --from=base --chown=node:node /app/server ./server
COPY --from=base --chown=node:node /app/package.json ./
COPY --from=base --chown=node:node /app/yarn.lock ./
COPY --from=base --chown=node:node /app/node_modules ./node_modules

# node_modules уже установлены в базовом слое; повторная установка не требуется

# Expose application port
USER node
EXPOSE ${PORT}

# Start the server
CMD ["node", "./server/server.mjs"]
