# syntax=docker/dockerfile:1
FROM node:23-alpine AS base
WORKDIR /app

# Установка переменных окружения ДЛЯ СБОРКИ
ARG NODE_BACKEND_ENDPOINT=http://77.37.136.11:7070
ARG NODE_ALERT_ENDPOINT=http://77.37.136.11:7080
ARG NODE_MODEL_FAST_API_ENDPOINT=http://77.37.136.11:7072
ARG NODE_ORCHESTRATOR_ENDPOINT=http://77.37.136.11:7071

ARG VITE_BACKEND_ENDPOINT=/backend_endpoint
ARG VITE_ALERT_ENDPOINT=/alert_endpoint
ARG VITE_MODEL_FAST_API_ENDPOINT=/model_fast_api_endpoint
ARG VITE_ORCHESTRATOR_ENDPOINT=/orchestrator
ARG VITE_ORCHESTRATOR_PATH_PREFIX=horizon_orchestrator
ARG VITE_ORCHESTRATOR_TOKEN=zfd2oosl2RGqsdKpBA9MSrYlSfafQqXF1q9PuPCxi9LqtwDQva58SSH7pr7wldhe

# Преобразование ARG в ENV для РАНТАЙМА
ENV NODE_BACKEND_ENDPOINT=$NODE_BACKEND_ENDPOINT
ENV NODE_ALERT_ENDPOINT=$NODE_ALERT_ENDPOINT
ENV NODE_MODEL_FAST_API_ENDPOINT=$NODE_MODEL_FAST_API_ENDPOINT
ENV NODE_ORCHESTRATOR_ENDPOINT=$NODE_ORCHESTRATOR_ENDPOINT

ENV VITE_BACKEND_ENDPOINT=$VITE_BACKEND_ENDPOINT
ENV VITE_ALERT_ENDPOINT=$VITE_ALERT_ENDPOINT
ENV VITE_MODEL_FAST_API_ENDPOINT=$VITE_MODEL_FAST_API_ENDPOINT
ENV VITE_ORCHESTRATOR_ENDPOINT=$VITE_ORCHESTRATOR_ENDPOINT
ENV VITE_ORCHESTRATOR_PATH_PREFIX=$VITE_ORCHESTRATOR_PATH_PREFIX
ENV VITE_ORCHESTRATOR_TOKEN=$VITE_ORCHESTRATOR_TOKEN

RUN apk update && apk upgrade && \
    apk add --no-cache libc6-compat && \
    npm install -g corepack && \
    corepack enable && \
    corepack prepare yarn@4.9.1 --activate

COPY . .
RUN yarn install --immutable
RUN yarn build

FROM node:23-alpine AS production
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

# Копируем ВСЕ переменные окружения из builder stage
ENV NODE_BACKEND_ENDPOINT=$NODE_BACKEND_ENDPOINT
ENV NODE_ALERT_ENDPOINT=$NODE_ALERT_ENDPOINT
ENV NODE_MODEL_FAST_API_ENDPOINT=$NODE_MODEL_FAST_API_ENDPOINT
ENV NODE_ORCHESTRATOR_ENDPOINT=$NODE_ORCHESTRATOR_ENDPOINT

ENV VITE_BACKEND_ENDPOINT=$VITE_BACKEND_ENDPOINT
ENV VITE_ALERT_ENDPOINT=$VITE_ALERT_ENDPOINT
ENV VITE_MODEL_FAST_API_ENDPOINT=$VITE_MODEL_FAST_API_ENDPOINT
ENV VITE_ORCHESTRATOR_ENDPOINT=$VITE_ORCHESTRATOR_ENDPOINT
ENV VITE_ORCHESTRATOR_PATH_PREFIX=$VITE_ORCHESTRATOR_PATH_PREFIX
ENV VITE_ORCHESTRATOR_TOKEN=$VITE_ORCHESTRATOR_TOKEN

RUN apk add --no-cache libc6-compat

COPY --from=base --chown=node:node /app/dist ./dist
COPY --from=base --chown=node:node /app/server ./server
COPY --from=base --chown=node:node /app/package.json ./

RUN yarn workspaces focus --production

USER node
EXPOSE ${PORT}

CMD ["node", "./server/server.mjs"]